### ISSUE TITLE
feat: femboy breeding :trol:

### ISSUE THREAD

**Issue by ghost** [toastxc/Reywen-Revolt#37]
when a mommy femboy and a daddy femboy love each other very much they

**Comment by toastxc** [comment]
uhm
is this a feature request?

**Comment by ghost** [comment]
yes

**Comment by toastxc** [comment]
can you provide more details please

**Comment by toastxc** [comment]
also, this isn't the repository for the Reywen bot, that's here 
https://github.com/toastxc/Reywen-TXC

**Comment by ghost** [comment]
https://github.com/toastxc/Reywen-TXC/issues/1
