### ISSUE TITLE
Plural plugin no longer functional?

### ISSUE THREAD

**Issue by zauberparacelsus** [toastxc/Reywen-Revolt#40]
The Plural plugin no longer appears to be functional.  The help command works, but search, query, rm, insert, and send commands all silently fail.  I've tried using it on two different revolt servers (including my own), and have also tried DMing it directly, but in all cases it is the same behavior: the help command works, but nothing else.

**Comment by toastxc** [comment]
Hi, this issue is replicatable and i found the cause
the MongoDB instance for ReywenTXC was not running properly and it has been restarted

**Comment by toastxc** [comment]
Although it should never have gone down in the first place, that I will try to fix

**Comment by zauberparacelsus** [comment]
Well, looks like it is down again

**Comment by toastxc** [comment]
not good...
Im sorry this issue exists at all, reywenV2 has some serious availability issues to do with databases and its really not good enough


I've completed a full rewrite of the library in a private repo and im aiming to publish today and make a dedicated plural bot with it.

**Comment by toastxc** [comment]
as a temporary fix the DB has been restarted, there isnt any clear indication as of why this is happening but i will figure it out
